/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Calculator;

import com.sun.glass.events.KeyEvent;

/**
 *
 * @author Austine
 */
public class Calculator extends javax.swing.JFrame {

    
    double num1;
    double num2;
    String op;
    Double result;
    private Object math;
    
    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
        on.setSelected(true);
        setTitle("Calculator");
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tdisplay = new javax.swing.JTextField();
        C_btn = new javax.swing.JButton();
        back_btn = new javax.swing.JButton();
        CE_btn = new javax.swing.JButton();
        div_btn = new javax.swing.JButton();
        btn_8 = new javax.swing.JButton();
        btn_9 = new javax.swing.JButton();
        btn_7 = new javax.swing.JButton();
        mul_btn = new javax.swing.JButton();
        btn_5 = new javax.swing.JButton();
        btn_6 = new javax.swing.JButton();
        btn_4 = new javax.swing.JButton();
        sub_btn = new javax.swing.JButton();
        btn_2 = new javax.swing.JButton();
        btn_3 = new javax.swing.JButton();
        btn_1 = new javax.swing.JButton();
        add_btn = new javax.swing.JButton();
        btn_0 = new javax.swing.JButton();
        dot_btn = new javax.swing.JButton();
        sign_btn = new javax.swing.JButton();
        equal_btn = new javax.swing.JButton();
        mod_btn = new javax.swing.JButton();
        sqrt_btn = new javax.swing.JButton();
        pow2_btn = new javax.swing.JButton();
        recipocal_btn = new javax.swing.JButton();
        on = new javax.swing.JRadioButton();
        off = new javax.swing.JRadioButton();
        tan_btn = new javax.swing.JButton();
        tanh_btn = new javax.swing.JButton();
        curoot_btn = new javax.swing.JButton();
        round_btn = new javax.swing.JButton();
        log_btn = new javax.swing.JButton();
        ln_btn = new javax.swing.JButton();
        pi_btn = new javax.swing.JButton();
        factorial_btn = new javax.swing.JButton();
        sin_btn = new javax.swing.JButton();
        cos_btn = new javax.swing.JButton();
        cosh_btn = new javax.swing.JButton();
        oct_btn = new javax.swing.JButton();
        powxy_btn = new javax.swing.JButton();
        pow3_btn = new javax.swing.JButton();
        pow10x_btn = new javax.swing.JButton();
        bin_btn = new javax.swing.JButton();
        hex_btn = new javax.swing.JButton();
        sinh_btn = new javax.swing.JButton();
        Ldisplay = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(375, 610));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        Tdisplay.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Tdisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Tdisplay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TdisplayKeyTyped(evt);
            }
        });

        C_btn.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        C_btn.setText("C");
        C_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_btnActionPerformed(evt);
            }
        });

        back_btn.setFont(new java.awt.Font("Cambria Math", 1, 36)); // NOI18N
        back_btn.setText("←");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });

        CE_btn.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        CE_btn.setText("CE");
        CE_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CE_btnActionPerformed(evt);
            }
        });

        div_btn.setFont(new java.awt.Font("Cambria Math", 1, 30)); // NOI18N
        div_btn.setText("÷");
        div_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                div_btnActionPerformed(evt);
            }
        });

        btn_8.setBackground(new java.awt.Color(255, 255, 255));
        btn_8.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btn_8.setText("8");
        btn_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_8ActionPerformed(evt);
            }
        });

        btn_9.setBackground(new java.awt.Color(255, 255, 255));
        btn_9.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btn_9.setText("9");
        btn_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_9ActionPerformed(evt);
            }
        });

        btn_7.setBackground(new java.awt.Color(255, 255, 255));
        btn_7.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btn_7.setText("7");
        btn_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_7ActionPerformed(evt);
            }
        });

        mul_btn.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        mul_btn.setText("X");
        mul_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mul_btnActionPerformed(evt);
            }
        });

        btn_5.setBackground(new java.awt.Color(255, 255, 255));
        btn_5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btn_5.setText("5");
        btn_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_5ActionPerformed(evt);
            }
        });

        btn_6.setBackground(new java.awt.Color(255, 255, 255));
        btn_6.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btn_6.setText("6");
        btn_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_6ActionPerformed(evt);
            }
        });

        btn_4.setBackground(new java.awt.Color(255, 255, 255));
        btn_4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btn_4.setText("4");
        btn_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_4ActionPerformed(evt);
            }
        });

        sub_btn.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        sub_btn.setText("-");
        sub_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_btnActionPerformed(evt);
            }
        });

        btn_2.setBackground(new java.awt.Color(255, 255, 255));
        btn_2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btn_2.setText("2");
        btn_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_2ActionPerformed(evt);
            }
        });

        btn_3.setBackground(new java.awt.Color(255, 255, 255));
        btn_3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btn_3.setText("3");
        btn_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_3ActionPerformed(evt);
            }
        });

        btn_1.setBackground(new java.awt.Color(255, 255, 255));
        btn_1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btn_1.setText("1");
        btn_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_1ActionPerformed(evt);
            }
        });

        add_btn.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        add_btn.setText("+");
        add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btnActionPerformed(evt);
            }
        });

        btn_0.setBackground(new java.awt.Color(255, 255, 255));
        btn_0.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btn_0.setText("0");
        btn_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_0ActionPerformed(evt);
            }
        });

        dot_btn.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        dot_btn.setText(".");
        dot_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dot_btnActionPerformed(evt);
            }
        });

        sign_btn.setFont(new java.awt.Font("Centaur", 1, 20)); // NOI18N
        sign_btn.setText("±");
        sign_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sign_btnActionPerformed(evt);
            }
        });

        equal_btn.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        equal_btn.setText("=");
        equal_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equal_btnActionPerformed(evt);
            }
        });

        mod_btn.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        mod_btn.setText("%");
        mod_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mod_btnActionPerformed(evt);
            }
        });

        sqrt_btn.setFont(new java.awt.Font("Cambria Math", 1, 20)); // NOI18N
        sqrt_btn.setText("√");
        sqrt_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqrt_btnActionPerformed(evt);
            }
        });

        pow2_btn.setFont(new java.awt.Font("Cambria Math", 1, 20)); // NOI18N
        pow2_btn.setText("x^2");
        pow2_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pow2_btnActionPerformed(evt);
            }
        });

        recipocal_btn.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        recipocal_btn.setText("1/x");
        recipocal_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recipocal_btnActionPerformed(evt);
            }
        });

        on.setText("ON");
        on.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onActionPerformed(evt);
            }
        });

        off.setText("OFF");
        off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                offActionPerformed(evt);
            }
        });

        tan_btn.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        tan_btn.setText("Tan");
        tan_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tan_btnActionPerformed(evt);
            }
        });

        tanh_btn.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        tanh_btn.setText("Tanh");
        tanh_btn.setMargin(new java.awt.Insets(2, 0, 2, 0));
        tanh_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanh_btnActionPerformed(evt);
            }
        });

        curoot_btn.setFont(new java.awt.Font("Cambria Math", 1, 20)); // NOI18N
        curoot_btn.setText("∛");
        curoot_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                curoot_btnActionPerformed(evt);
            }
        });

        round_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        round_btn.setText("Roud");
        round_btn.setMargin(new java.awt.Insets(2, 0, 2, 0));
        round_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                round_btnActionPerformed(evt);
            }
        });

        log_btn.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        log_btn.setText("Log");
        log_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_btnActionPerformed(evt);
            }
        });

        ln_btn.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        ln_btn.setText("ln");
        ln_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ln_btnActionPerformed(evt);
            }
        });

        pi_btn.setFont(new java.awt.Font("Cambria Math", 1, 20)); // NOI18N
        pi_btn.setText("𝝅");
        pi_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pi_btnActionPerformed(evt);
            }
        });

        factorial_btn.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        factorial_btn.setText("n!");
        factorial_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factorial_btnActionPerformed(evt);
            }
        });

        sin_btn.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        sin_btn.setText("Sin");
        sin_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sin_btnActionPerformed(evt);
            }
        });

        cos_btn.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        cos_btn.setText("Cos");
        cos_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cos_btnActionPerformed(evt);
            }
        });

        cosh_btn.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        cosh_btn.setText("Cosh");
        cosh_btn.setMargin(new java.awt.Insets(2, 0, 2, 0));
        cosh_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosh_btnActionPerformed(evt);
            }
        });

        oct_btn.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        oct_btn.setText("Oct");
        oct_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oct_btnActionPerformed(evt);
            }
        });

        powxy_btn.setFont(new java.awt.Font("Cambria Math", 1, 20)); // NOI18N
        powxy_btn.setText("x^y");
        powxy_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powxy_btnActionPerformed(evt);
            }
        });

        pow3_btn.setFont(new java.awt.Font("Cambria Math", 1, 20)); // NOI18N
        pow3_btn.setText("x^3");
        pow3_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pow3_btnActionPerformed(evt);
            }
        });

        pow10x_btn.setFont(new java.awt.Font("Cambria Math", 1, 20)); // NOI18N
        pow10x_btn.setText("10^x");
        pow10x_btn.setMargin(new java.awt.Insets(2, 0, 2, 0));
        pow10x_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pow10x_btnActionPerformed(evt);
            }
        });

        bin_btn.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        bin_btn.setText("Bin");
        bin_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bin_btnActionPerformed(evt);
            }
        });

        hex_btn.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        hex_btn.setText("Hex");
        hex_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hex_btnActionPerformed(evt);
            }
        });

        sinh_btn.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        sinh_btn.setText("Sinh");
        sinh_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinh_btnActionPerformed(evt);
            }
        });

        Ldisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Standard");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Scientific");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(on)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(off))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CE_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(C_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(div_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_7, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_8, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_9, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(mul_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sub_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sign_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_0, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dot_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(equal_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mod_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sqrt_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pow2_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(recipocal_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cos_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cosh_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tan_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tanh_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(curoot_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(round_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(log_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ln_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pi_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(factorial_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sin_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sinh_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hex_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(oct_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(powxy_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pow3_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pow10x_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bin_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Ldisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tdisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Tdisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Ldisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(on)
                    .addComponent(off))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sqrt_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pow2_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mod_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(recipocal_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(C_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CE_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(div_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mul_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sub_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_0, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dot_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sign_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(equal_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sin_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sinh_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cos_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tan_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tanh_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(curoot_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(round_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(log_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ln_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pi_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(factorial_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bin_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hex_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cosh_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(oct_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(powxy_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pow3_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pow10x_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        
        this.setResizable(true);
        Tdisplay.setSize(600,60);
        Ldisplay.setSize(600,37);
        
        this.setSize(630, 610);
        //this.setResizable(false);
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.setResizable(true);
        this.setSize(375, 610);
        //this.setResizable(false);
    }//GEN-LAST:event_formWindowActivated

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.setResizable(true);
        this.setSize(375, 610);   
        on.setSelected(true);
        //this.setResizable(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btn_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_7ActionPerformed
        Tdisplay.setText(Tdisplay.getText()+"7");
    }//GEN-LAST:event_btn_7ActionPerformed

    private void btn_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_8ActionPerformed
    Tdisplay.setText(Tdisplay.getText()+"8");
    }//GEN-LAST:event_btn_8ActionPerformed

    private void btn_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_9ActionPerformed
       Tdisplay.setText(Tdisplay.getText()+"9");
    }//GEN-LAST:event_btn_9ActionPerformed

    private void btn_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_4ActionPerformed
       Tdisplay.setText(Tdisplay.getText()+"4");
    }//GEN-LAST:event_btn_4ActionPerformed

    private void btn_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_5ActionPerformed
        Tdisplay.setText(Tdisplay.getText()+"5");
    }//GEN-LAST:event_btn_5ActionPerformed

    private void btn_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_6ActionPerformed
       Tdisplay.setText(Tdisplay.getText()+"6");
    }//GEN-LAST:event_btn_6ActionPerformed

    private void btn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_1ActionPerformed
        Tdisplay.setText(Tdisplay.getText()+"1");
    }//GEN-LAST:event_btn_1ActionPerformed

    private void btn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_2ActionPerformed
       Tdisplay.setText(Tdisplay.getText()+"2");
    }//GEN-LAST:event_btn_2ActionPerformed

    private void btn_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_3ActionPerformed
        Tdisplay.setText(Tdisplay.getText()+"3");
    }//GEN-LAST:event_btn_3ActionPerformed

    private void btn_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_0ActionPerformed
       Tdisplay.setText(Tdisplay.getText()+"0");
    }//GEN-LAST:event_btn_0ActionPerformed

    private void C_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_btnActionPerformed

        Tdisplay.setText(null);
        Ldisplay.setText(null);
    }//GEN-LAST:event_C_btnActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        if(Tdisplay.getText().length()>0)
        {
            StringBuilder s=new StringBuilder(Tdisplay.getText());
            s.deleteCharAt(Tdisplay.getText().length()-1);
            Tdisplay.setText(s.toString());
        }
    }//GEN-LAST:event_back_btnActionPerformed

    private void dot_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dot_btnActionPerformed
        if(!Tdisplay.getText().contains("."))
        {
            Tdisplay.setText(Tdisplay.getText()+".");
        }
    }//GEN-LAST:event_dot_btnActionPerformed

    private void sign_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sign_btnActionPerformed
        Double num=Double.parseDouble(String.valueOf(Tdisplay.getText()));
        num*=-1;
        Tdisplay.setText(String.valueOf(num));
    }//GEN-LAST:event_sign_btnActionPerformed

    private void sqrt_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqrt_btnActionPerformed
        try{
        Double num=Double.parseDouble(String.valueOf(Tdisplay.getText()));
        num=Math.sqrt(num);
        Tdisplay.setText(String.valueOf(num));}
        catch(Exception e)
        {
            Tdisplay.setText("Error");
        }
    }//GEN-LAST:event_sqrt_btnActionPerformed

    private void pow2_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pow2_btnActionPerformed
        Double num=Double.parseDouble(String.valueOf(Tdisplay.getText()));
        num=Math.pow(num,2);
        Tdisplay.setText(String.valueOf(num));
    }//GEN-LAST:event_pow2_btnActionPerformed

    private void recipocal_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recipocal_btnActionPerformed
       Double num=Double.parseDouble(String.valueOf(Tdisplay.getText()));
        num=1/num;
        Tdisplay.setText(String.valueOf(num));
    }//GEN-LAST:event_recipocal_btnActionPerformed

    private void pow3_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pow3_btnActionPerformed
       Double num=Double.parseDouble(String.valueOf(Tdisplay.getText()));
        num=Math.pow(num,3);
        Tdisplay.setText(String.valueOf(num));
    }//GEN-LAST:event_pow3_btnActionPerformed

    private void pow10x_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pow10x_btnActionPerformed
       Double num=Double.parseDouble(String.valueOf(Tdisplay.getText()));
        num=Math.pow(10,num);
        Tdisplay.setText(String.valueOf(num));
    }//GEN-LAST:event_pow10x_btnActionPerformed

    private void curoot_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_curoot_btnActionPerformed
       Double num=Double.parseDouble(String.valueOf(Tdisplay.getText()));
        num=Math.cbrt(num);
        Tdisplay.setText(String.valueOf(num));
    }//GEN-LAST:event_curoot_btnActionPerformed

    private void sin_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sin_btnActionPerformed
        Double num=Double.parseDouble(String.valueOf(Tdisplay.getText()));
        num=Math.sin(num);
        Tdisplay.setText(String.valueOf(num));
    }//GEN-LAST:event_sin_btnActionPerformed

    private void cos_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cos_btnActionPerformed
        Double num=Double.parseDouble(String.valueOf(Tdisplay.getText()));
        num=Math.cos(num);
        Tdisplay.setText(String.valueOf(num));
    }//GEN-LAST:event_cos_btnActionPerformed

    private void tan_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tan_btnActionPerformed
        Double num=Double.parseDouble(String.valueOf(Tdisplay.getText()));
        num=Math.tan(num);
        Tdisplay.setText(String.valueOf(num));
    }//GEN-LAST:event_tan_btnActionPerformed

    private void sinh_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinh_btnActionPerformed
        Double num=Double.parseDouble(String.valueOf(Tdisplay.getText()));
        num=Math.sinh(num);
        Tdisplay.setText(String.valueOf(num));
    }//GEN-LAST:event_sinh_btnActionPerformed

    private void cosh_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosh_btnActionPerformed
        Double num=Double.parseDouble(String.valueOf(Tdisplay.getText()));
        num=Math.cosh(num);
        Tdisplay.setText(String.valueOf(num));
    }//GEN-LAST:event_cosh_btnActionPerformed

    private void tanh_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanh_btnActionPerformed
        Double num=Double.parseDouble(String.valueOf(Tdisplay.getText()));
        num=Math.tanh(num);
        Tdisplay.setText(String.valueOf(num));
    }//GEN-LAST:event_tanh_btnActionPerformed

    private void log_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log_btnActionPerformed
        Double num=Double.parseDouble(String.valueOf(Tdisplay.getText()));
        num=Math.log(num);
        Tdisplay.setText(String.valueOf(num));
    }//GEN-LAST:event_log_btnActionPerformed

    private void ln_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ln_btnActionPerformed
        Double num=Double.parseDouble(String.valueOf(Tdisplay.getText()));
        num=Math.log10(num);
        Tdisplay.setText(String.valueOf(num));
    }//GEN-LAST:event_ln_btnActionPerformed

    private void factorial_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factorial_btnActionPerformed
        Double num=Double.parseDouble(String.valueOf(Tdisplay.getText()));
        Double i,ans;
        i=1.0;
        ans=1.0;
        while(i<=num)
        {
            ans*=i;
            i++;
        }
         Tdisplay.setText(String.valueOf(ans));
    }//GEN-LAST:event_factorial_btnActionPerformed

    private void pi_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pi_btnActionPerformed
        Tdisplay.setText("3.1415926535897932384626433832795");
    }//GEN-LAST:event_pi_btnActionPerformed

    private void round_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_round_btnActionPerformed
        Double num=Double.parseDouble(String.valueOf(Tdisplay.getText()));
        long rnum;
        rnum=Math.round(num);
        Tdisplay.setText(String.valueOf(rnum));
    }//GEN-LAST:event_round_btnActionPerformed

    private void bin_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bin_btnActionPerformed
        int num=Integer.parseInt(Tdisplay.getText());
        Tdisplay.setText(Integer.toBinaryString(num));
    }//GEN-LAST:event_bin_btnActionPerformed

    private void hex_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hex_btnActionPerformed
        int num=Integer.parseInt(Tdisplay.getText());
        Tdisplay.setText(Integer.toHexString(num));
    }//GEN-LAST:event_hex_btnActionPerformed

    private void oct_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oct_btnActionPerformed
        int num=Integer.parseInt(Tdisplay.getText());
        Tdisplay.setText(Integer.toOctalString(num));
    }//GEN-LAST:event_oct_btnActionPerformed

    private void TdisplayKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TdisplayKeyTyped
        char ch=evt.getKeyChar();
        if(!(Character.isDigit(ch)||(ch==KeyEvent.VK_BACKSPACE)||(ch==KeyEvent.VK_DELETE))){
            getToolkit().beep();
        evt.consume();
        }
    }//GEN-LAST:event_TdisplayKeyTyped

    private void equal_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equal_btnActionPerformed
        String ans;
        if(Tdisplay.getText().isEmpty())
            num2=0;
        else       
            num2=Double.parseDouble(Tdisplay.getText());
        if(op=="+")
        {
            result=num1+num2;
            ans=String.format("%.2f", result);
        }
        else if(op=="-")
        {
            result=num1-num2;
            ans=String.format("%.2f", result);
        }
        else if(op=="*")
        {
            result=num1*num2;
            ans=String.format("%.2f", result);
        }
        else if(op=="/")
        {
            result=num1/num2;
            ans=String.format("%.2f", result);
        }
        else if(op=="%")
        {
            result=num1%num2;
            ans=String.format("%.2f", result);
        }
        else if(op=="^")
        {
            result=Math.pow(num1,num2);
            ans=String.format("%.2f", result);
        }
        else
            ans="Error";
        Ldisplay.setText(Ldisplay.getText()+" "+num2);
        Tdisplay.setText("= "+ans);
    }//GEN-LAST:event_equal_btnActionPerformed

    private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btnActionPerformed
       if(Tdisplay.getText().length()>0&&Ldisplay.getText().length()>0)
       {
           num1=result;
           Ldisplay.setText(num1+" +");
           Tdisplay.setText(null);
           Tdisplay.setText("");
       }   
       else if(Ldisplay.getText().length()>0)
       {
           num1=num1+Double.parseDouble(Tdisplay.getText());
           Ldisplay.setText(String.valueOf(num1)+" +");
           Tdisplay.setText(null);
           op="+";
       }
       
       else
       {
            num1=Double.parseDouble(Tdisplay.getText());
            Ldisplay.setText(String.valueOf(num1)+" +");
            Tdisplay.setText(null);
            op="+";
       }
        
    }//GEN-LAST:event_add_btnActionPerformed

    private void sub_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub_btnActionPerformed
       if(Tdisplay.getText().length()>0&&Ldisplay.getText().length()>0)
       {
           num1=result;
           Ldisplay.setText(num1+" -");
           Tdisplay.setText(null);
       }   
       else  if(Ldisplay.getText().length()>0)
       {
           num1=num1-Double.parseDouble(Tdisplay.getText());
           Ldisplay.setText(String.valueOf(num1)+" -");
           Tdisplay.setText(null);
           op="-";
       }
       
       else
       {
            num1=Double.parseDouble(Tdisplay.getText());
            Ldisplay.setText(String.valueOf(num1)+" -");
            Tdisplay.setText(null);
            op="-";
       }
    }//GEN-LAST:event_sub_btnActionPerformed

    private void mul_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mul_btnActionPerformed
       if(Tdisplay.getText().length()>0&&Ldisplay.getText().length()>0)
       {
           num1=result;
           Ldisplay.setText(num1+" X");
           Tdisplay.setText(null);
       }   
        else if(Ldisplay.getText().length()>0)
       {
           num1=num1*Double.parseDouble(Tdisplay.getText());
           Ldisplay.setText(String.valueOf(num1)+" X");
           Tdisplay.setText(null);
           op="*";
       }
       
       else
       {
            num1=Double.parseDouble(Tdisplay.getText());
            Ldisplay.setText(String.valueOf(num1)+" X");
            Tdisplay.setText(null);
            op="*";
       }
    }//GEN-LAST:event_mul_btnActionPerformed

    private void mod_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mod_btnActionPerformed
        if(Tdisplay.getText().length()>0&&Ldisplay.getText().length()>0)
       {
           num1=result;
           Ldisplay.setText(num1+" %");
           Tdisplay.setText(null);
       }   
        else if(Ldisplay.getText().length()>0)
       {
           num1=num1%Double.parseDouble(Tdisplay.getText());
           Ldisplay.setText(String.valueOf(num1)+" %");
           Tdisplay.setText(null);
           op="%";
       }
       
       else
       {
            num1=Double.parseDouble(Tdisplay.getText());
            Ldisplay.setText(String.valueOf(num1)+" %");
            Tdisplay.setText(null);
            op="%";
       }
    }//GEN-LAST:event_mod_btnActionPerformed

    private void div_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_div_btnActionPerformed
       try{
        if(Tdisplay.getText().length()>0&&Ldisplay.getText().length()>0)
       {
           num1=result;
           Ldisplay.setText(num1+" /");
           Tdisplay.setText(null);
       }   
       /*else if(Ldisplay.getText().length()>0)
       {
           num1=num1/Double.parseDouble(Tdisplay.getText());
           Ldisplay.setText(String.valueOf(num1)+" /");
           Tdisplay.setText(null);
           op="/";
       }*/
       
       else
       {
            num1=Double.parseDouble(Tdisplay.getText());
            Ldisplay.setText(String.valueOf(num1)+" /");
            Tdisplay.setText(null);
            op="/";
       }
       }
       catch(Exception e)
       {
           Tdisplay.setText("Error");
       }
    }//GEN-LAST:event_div_btnActionPerformed

    private void CE_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CE_btnActionPerformed
        Ldisplay.setText(null);
    }//GEN-LAST:event_CE_btnActionPerformed

    private void powxy_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powxy_btnActionPerformed
        if(Tdisplay.getText().length()>0&&Ldisplay.getText().length()>0)
       {
           num1=result;
           Ldisplay.setText(num1+" ^");
           Tdisplay.setText(null);
       }   
       else if(Ldisplay.getText().length()>0)
       {
           num1=Math.pow(num1,Double.parseDouble(Tdisplay.getText()));
           Ldisplay.setText(String.valueOf(num1)+" ^");
           Tdisplay.setText(null);
           op="^";
       }
       
       else
       {
            num1=Double.parseDouble(Tdisplay.getText());
            Ldisplay.setText(String.valueOf(num1)+" ^");
            Tdisplay.setText(null);
            op="^";
       }
    }//GEN-LAST:event_powxy_btnActionPerformed

    private void offActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_offActionPerformed
        if(off.isSelected())
        {
            on.setSelected(false);
            Tdisplay.setText(null);
            Ldisplay.setText(null);
            CE_btn.setEnabled(false);
            C_btn.setEnabled(false);
            Ldisplay.setEnabled(false);
            Tdisplay.setEnabled(false);
            add_btn.setEnabled(false);
            back_btn.setEnabled(false);
            bin_btn.setEnabled(false);
            btn_0.setEnabled(false);
            btn_1.setEnabled(false);
            btn_2.setEnabled(false);
            btn_3.setEnabled(false);
            btn_4.setEnabled(false);
            btn_5.setEnabled(false);
            btn_6.setEnabled(false);
            btn_7.setEnabled(false);
            btn_8.setEnabled(false);
            btn_9.setEnabled(false);
            cos_btn.setEnabled(false);
            cosh_btn.setEnabled(false);
            curoot_btn.setEnabled(false);
            div_btn.setEnabled(false);
            dot_btn.setEnabled(false);
            equal_btn.setEnabled(false);
            factorial_btn.setEnabled(false);
            hex_btn.setEnabled(false);
            ln_btn.setEnabled(false);
            log_btn.setEnabled(false);
            mod_btn.setEnabled(false);
            mul_btn.setEnabled(false);
            oct_btn.setEnabled(false);
            pi_btn.setEnabled(false);
            pow10x_btn.setEnabled(false);
            pow2_btn.setEnabled(false);
            pow3_btn.setEnabled(false);
            powxy_btn.setEnabled(false);
            recipocal_btn.setEnabled(false);
            round_btn.setEnabled(false);
            sign_btn.setEnabled(false);
            sin_btn.setEnabled(false);
            sinh_btn.setEnabled(false);
            sqrt_btn.setEnabled(false);
            sub_btn.setEnabled(false);
            tan_btn.setEnabled(false);
            tanh_btn.setEnabled(false);
        }
    }//GEN-LAST:event_offActionPerformed

    private void onActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onActionPerformed
        if(on.isSelected())
        {
            off.setSelected(false);
            
            CE_btn.setEnabled(true);
            C_btn.setEnabled(true);
            Ldisplay.setEnabled(true);
            Tdisplay.setEnabled(true);
            add_btn.setEnabled(true);
            back_btn.setEnabled(true);
            bin_btn.setEnabled(true);
            btn_0.setEnabled(true);
            btn_1.setEnabled(true);
            btn_2.setEnabled(true);
            btn_3.setEnabled(true);
            btn_4.setEnabled(true);
            btn_5.setEnabled(true);
            btn_6.setEnabled(true);
            btn_7.setEnabled(true);
            btn_8.setEnabled(true);
            btn_9.setEnabled(true);
            cos_btn.setEnabled(true);
            cosh_btn.setEnabled(true);
            curoot_btn.setEnabled(true);
            div_btn.setEnabled(true);
            dot_btn.setEnabled(true);
            equal_btn.setEnabled(true);
            factorial_btn.setEnabled(true);
            hex_btn.setEnabled(true);
            ln_btn.setEnabled(true);
            log_btn.setEnabled(true);
            mod_btn.setEnabled(true);
            mul_btn.setEnabled(true);
            oct_btn.setEnabled(true);
            pi_btn.setEnabled(true);
            pow10x_btn.setEnabled(true);
            pow2_btn.setEnabled(true);
            pow3_btn.setEnabled(true);
            powxy_btn.setEnabled(true);
            recipocal_btn.setEnabled(true);
            round_btn.setEnabled(true);
            sign_btn.setEnabled(true);
            sin_btn.setEnabled(true);
            sinh_btn.setEnabled(true);
            sqrt_btn.setEnabled(true);
            sub_btn.setEnabled(true);
            tan_btn.setEnabled(true);
            tanh_btn.setEnabled(true);
        }
    }//GEN-LAST:event_onActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CE_btn;
    private javax.swing.JButton C_btn;
    private javax.swing.JTextField Ldisplay;
    private javax.swing.JTextField Tdisplay;
    private javax.swing.JButton add_btn;
    private javax.swing.JButton back_btn;
    private javax.swing.JButton bin_btn;
    private javax.swing.JButton btn_0;
    private javax.swing.JButton btn_1;
    private javax.swing.JButton btn_2;
    private javax.swing.JButton btn_3;
    private javax.swing.JButton btn_4;
    private javax.swing.JButton btn_5;
    private javax.swing.JButton btn_6;
    private javax.swing.JButton btn_7;
    private javax.swing.JButton btn_8;
    private javax.swing.JButton btn_9;
    private javax.swing.JButton cos_btn;
    private javax.swing.JButton cosh_btn;
    private javax.swing.JButton curoot_btn;
    private javax.swing.JButton div_btn;
    private javax.swing.JButton dot_btn;
    private javax.swing.JButton equal_btn;
    private javax.swing.JButton factorial_btn;
    private javax.swing.JButton hex_btn;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JButton ln_btn;
    private javax.swing.JButton log_btn;
    private javax.swing.JButton mod_btn;
    private javax.swing.JButton mul_btn;
    private javax.swing.JButton oct_btn;
    private javax.swing.JRadioButton off;
    private javax.swing.JRadioButton on;
    private javax.swing.JButton pi_btn;
    private javax.swing.JButton pow10x_btn;
    private javax.swing.JButton pow2_btn;
    private javax.swing.JButton pow3_btn;
    private javax.swing.JButton powxy_btn;
    private javax.swing.JButton recipocal_btn;
    private javax.swing.JButton round_btn;
    private javax.swing.JButton sign_btn;
    private javax.swing.JButton sin_btn;
    private javax.swing.JButton sinh_btn;
    private javax.swing.JButton sqrt_btn;
    private javax.swing.JButton sub_btn;
    private javax.swing.JButton tan_btn;
    private javax.swing.JButton tanh_btn;
    // End of variables declaration//GEN-END:variables
}
